services:
  main:
    container_name: test-crud
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - test-crud-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:localpass2020@postgres:5432/test-crud
    depends_on:
      - postgres

  postgres:
    container_name: test-crud-postgres
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - test-crud-network
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localpass2020
      - POSTGRES_DB=test-crud

networks:
  test-crud-network:
